name: luminary
version: '3.9'

services:
  django:
    build:
      context: ./backend
    image: luminary-django
    container_name: django_app
    restart: always
    working_dir: /backend
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - environments_data:/backend/environments
      - ./backend:/backend

  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    ports:
      - "1234:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7.4
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - redis_data:/data

volumes:
  environments_data:
  postgres_data:
  redis_data:
